# Generated by Django 3.0.4 on 2020-03-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimonial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender_answer',
        ),
        migrations.RemoveField(
            model_name='person',
            name='year_of_birth_answer',
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='year_of_birth',
            field=models.CharField(default=1900, max_length=50, verbose_name='Year of Birth'),
            preserve_default=False,
        ),
    ]
